server:
  port: 8888
spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: consumer_route
          uri: lb://service-consumer
          predicates:
            - Path=/consumer/**
          #过滤器：如果请求有
          filters:
            - RewritePath=/consumer/(?<segment>.*),/$\{segment}
        - id: provider_route
          uri: lb://service-provider
          predicates:
            - Path=/provider/**
          filters:
            - RewritePath=/provider/(?<segment>.*),/$\{segment}

